export type Country = "nigeria" | "jamaica" | "zimbabwe" | "india";

export const COUNTRIES: Record<
  Country,
  { name: string; flag: string; color: string; cuisine: string }
> = {
  nigeria: { name: "Nigeria", flag: "🇳🇬", color: "#008751", cuisine: "Nigerian" },
  jamaica: { name: "Jamaica", flag: "🇯🇲", color: "#ffb81c", cuisine: "Jamaican" },
  zimbabwe: { name: "Zimbabwe", flag: "🇿🇼", color: "#ef3340", cuisine: "Zimbabwean" },
  india:    { name: "India",    flag: "🇮🇳", color: "#ff671f", cuisine: "Indian" },
};

// Unity Cup 2026 is held at The Valley, home of Charlton Athletic FC.
export const STADIUM = {
  name: "The Valley",
  subtitle: "Charlton Athletic FC",
  address: "Floyd Rd, Charlton, London SE7 8BL",
  lat: 51.4865,
  lng: 0.0364,
};

export type LatLng = { lat: number; lng: number };

// Haversine — distance between two lat/lng points in km.
export function distanceKm(a: LatLng, b: LatLng): number {
  const R = 6371;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

export function formatDistance(km: number): string {
  if (km < 1) return `${Math.round(km * 1000)} m`;
  if (km < 10) return `${km.toFixed(1)} km`;
  return `${Math.round(km)} km`;
}

export type Listing = {
  id: string;
  name: string;
  country: Country;
  type: "restaurant" | "cafe" | "bar" | "market" | "supper-club";
  area: string;
  address: string;
  lat: number;
  lng: number;
  summary: string;
  tags: string[];
  priceRange: "£" | "££" | "£££";
  featured?: boolean;
  url?: string;
};

export type EventItem = {
  id: string;
  title: string;
  country: Country | "all";
  type: "watch-party" | "meetup" | "pop-up" | "tournament";
  date: string;
  time: string;
  venue: string;
  area: string;
  lat: number;
  lng: number;
  summary: string;
};

// Real London-based venues across the four cuisines. Listings near The Valley
// (Charlton / Woolwich / Greenwich / Lewisham / Blackheath) are concentrated
// first so the "near stadium" view has plenty to show.
export const LISTINGS: Listing[] = [
  // ===== Near The Valley · Charlton / Woolwich =====
  {
    id: "j-rifas",
    name: "Rifa's Caribbean Cuisine",
    country: "jamaica",
    type: "restaurant",
    area: "Charlton",
    address: "Flat 5, Gooding House, Valley Grove, Charlton, London SE7 8AT",
    lat: 51.4860, lng: 0.0370,
    summary: "Caribbean kitchen a few minutes from The Valley — jerk, curry goat and patties.",
    tags: ["jerk", "curry goat", "near stadium"],
    priceRange: "£",
    featured: true,
  },
  {
    id: "i-new-viceroy",
    name: "New Viceroy",
    country: "india",
    type: "restaurant",
    area: "Charlton Village",
    address: "10 The Village, Charlton, London SE7 8UD",
    lat: 51.4854, lng: 0.0339,
    summary: "Charlton Village Indian dining room — curry-house classics and a long tandoori list.",
    tags: ["curry house", "tandoori", "near stadium"],
    priceRange: "££",
    featured: true,
  },
  {
    id: "i-kesar",
    name: "Kesar Punjabi Restaurant",
    country: "india",
    type: "restaurant",
    area: "Greenwich Peninsula",
    address: "192 Woolwich Rd, London SE7 7RA",
    lat: 51.4889, lng: 0.0234,
    summary: "Punjabi cooking on Woolwich Road, ten minutes' walk from the stadium.",
    tags: ["punjabi", "tandoori"],
    priceRange: "££",
  },
  {
    id: "j-real-deal",
    name: "The Real Deal Authentic Jamaican",
    country: "jamaica",
    type: "restaurant",
    area: "Woolwich",
    address: "17 Plumstead Rd, Woolwich, London SE18 7BZ",
    lat: 51.4902, lng: 0.0735,
    summary: "Woolwich Jamaican kitchen with delivery across the SE7, SE18 and SE28 postcodes.",
    tags: ["jerk", "takeaway", "delivery"],
    priceRange: "£",
  },
  {
    id: "j-chefs-house",
    name: "Chef's House",
    country: "jamaica",
    type: "restaurant",
    area: "Plumstead",
    address: "128 Plumstead Common Rd, Woolwich, London SE18 2UL",
    lat: 51.4815, lng: 0.0855,
    summary: "Neighbourhood Caribbean dining room on Plumstead Common.",
    tags: ["caribbean", "family-friendly"],
    priceRange: "££",
  },
  {
    id: "j-sunjam",
    name: "Sunjam Caribbean",
    country: "jamaica",
    type: "cafe",
    area: "Woolwich",
    address: "13A Spray St, Woolwich, London SE18 6AP",
    lat: 51.4905, lng: 0.0680,
    summary: "Quick Caribbean takeaway off Powis Street.",
    tags: ["takeaway", "lunch"],
    priceRange: "£",
  },
  {
    id: "n-tasty-woolwich",
    name: "Tasty Woolwich",
    country: "nigeria",
    type: "restaurant",
    area: "Woolwich",
    address: "16 Plumstead Rd, Woolwich, London SE18 7BZ",
    lat: 51.4901, lng: 0.0732,
    summary: "Plumstead Road West African kitchen with jollof, egusi and pepper soup.",
    tags: ["jollof", "egusi"],
    priceRange: "£",
    featured: true,
  },
  {
    id: "n-marys-takeaway",
    name: "Mary's Takeaway",
    country: "nigeria",
    type: "cafe",
    area: "Woolwich",
    address: "Unit 12, 125 Powis St, London SE18 6LQ",
    lat: 51.4906, lng: 0.0665,
    summary: "West African takeaway counter on Powis Street, popular for matchday lunches.",
    tags: ["takeaway", "matchday"],
    priceRange: "£",
  },
  {
    id: "n-ammas-fare",
    name: "Ammas Fare",
    country: "nigeria",
    type: "restaurant",
    area: "Woolwich",
    address: "179 Powis St, Woolwich, London SE18 6JL",
    lat: 51.4908, lng: 0.0664,
    summary: "Sit-down West African restaurant on the main Powis Street drag.",
    tags: ["sit-down", "west african"],
    priceRange: "££",
  },
  {
    id: "n-favourite-african",
    name: "Favourite African Restaurant",
    country: "nigeria",
    type: "restaurant",
    area: "Plumstead",
    address: "233 Plumstead High St, London SE18 1HF",
    lat: 51.4877, lng: 0.0860,
    summary: "Plumstead High Street West African spot with a hearty buffet-style menu.",
    tags: ["buffet", "west african"],
    priceRange: "£",
  },
  {
    id: "i-jatt-juliet",
    name: "Jatt & Juliet",
    country: "india",
    type: "bar",
    area: "Greenwich",
    address: "42 Woolwich Rd, London SE10 0JU",
    lat: 51.4889, lng: 0.0070,
    summary: "Modern Indian restaurant and bar between Greenwich and Charlton.",
    tags: ["modern indian", "cocktails"],
    priceRange: "££",
  },
  {
    id: "i-mountain-view",
    name: "Mountain View",
    country: "india",
    type: "restaurant",
    area: "Greenwich",
    address: "160 Trafalgar Rd, Greenwich, London SE10 9TZ",
    lat: 51.4825, lng: 0.0070,
    summary: "Greenwich Indian and Nepalese dining room near the Maritime Museum.",
    tags: ["indian", "nepalese"],
    priceRange: "££",
  },
  {
    id: "i-coriander",
    name: "The Coriander",
    country: "india",
    type: "restaurant",
    area: "Blackheath",
    address: "1-3 Station Crescent, London SE3 7EQ",
    lat: 51.4690, lng: 0.0140,
    summary: "Blackheath Indian local serving traditional and contemporary plates.",
    tags: ["curry house"],
    priceRange: "££",
  },

  // ===== Central & wider London =====
  {
    id: "n-ikoyi",
    name: "Ikoyi",
    country: "nigeria",
    type: "restaurant",
    area: "Strand",
    address: "180 Strand, London WC2R 1EA",
    lat: 51.5118, lng: -0.1163,
    summary: "Two-Michelin-star tasting menu drawing on West African ingredients and live-fire cooking.",
    tags: ["fine dining", "tasting menu", "michelin"],
    priceRange: "£££",
    featured: true,
    url: "https://ikoyilondon.com/",
  },
  {
    id: "n-akoko",
    name: "Akoko",
    country: "nigeria",
    type: "restaurant",
    area: "Fitzrovia",
    address: "21 Berners St, London W1T 3LP",
    lat: 51.5188, lng: -0.1370,
    summary: "Michelin-starred West African fine dining with a chef's-counter view of the grill.",
    tags: ["fine dining", "tasting menu", "michelin"],
    priceRange: "£££",
    url: "https://akoko.co.uk/",
  },
  {
    id: "n-akara",
    name: "Akara",
    country: "nigeria",
    type: "restaurant",
    area: "Borough",
    address: "Stoney St, Borough Yards, London SE1",
    lat: 51.5050, lng: -0.0908,
    summary: "Crispy akara fritters with rotating fillings, anchored by an open kitchen in Borough Yards.",
    tags: ["fritters", "open kitchen", "lunch"],
    priceRange: "££",
    url: "https://www.akaralondon.co.uk/",
  },
  {
    id: "n-chukus",
    name: "Chuku's",
    country: "nigeria",
    type: "restaurant",
    area: "Tottenham",
    address: "274 High Rd, Tottenham, London N15 4AJ",
    lat: 51.5880, lng: -0.0700,
    summary: "Brother-and-sister-run Nigerian tapas restaurant with small plates designed for sharing.",
    tags: ["tapas", "small plates", "family-run"],
    priceRange: "££",
    url: "https://chukuslondon.co.uk/",
  },
  {
    id: "n-805-peckham",
    name: "805 Restaurant · Peckham",
    country: "nigeria",
    type: "restaurant",
    area: "Peckham",
    address: "153 Rye Ln, Peckham, London SE15 4TL",
    lat: 51.4717, lng: -0.0698,
    summary: "Long-running London Nigerian chain serving jollof, egusi, suya and grilled fish into the night.",
    tags: ["jollof", "suya", "late night"],
    priceRange: "££",
    url: "https://www.805restaurants.com/",
  },
  {
    id: "n-eko",
    name: "Eko Wine Bar & Restaurant",
    country: "nigeria",
    type: "bar",
    area: "Homerton",
    address: "160 Homerton High St, London E9 6JA",
    lat: 51.5510, lng: -0.0440,
    summary: "Late-licence Nigerian wine bar with weekly live music and a hearty menu of home-style classics.",
    tags: ["wine bar", "live music", "late night"],
    priceRange: "££",
  },
  {
    id: "n-tatale",
    name: "Tatale",
    country: "nigeria",
    type: "restaurant",
    area: "Covent Garden",
    address: "The Africa Centre, 66 Great Suffolk St, London SE1 0BL",
    lat: 51.5036, lng: -0.0998,
    summary: "Modern West African plates from chef Akwasi Brenya-Mensa, named after a Ghanaian plantain dish.",
    tags: ["modern", "small plates"],
    priceRange: "£££",
    url: "https://www.tatale.co.uk/",
  },
  {
    id: "j-ma-petite",
    name: "Ma Petite Jamaica",
    country: "jamaica",
    type: "restaurant",
    area: "Camden",
    address: "9 Inverness St, Camden, London NW1 7HJ",
    lat: 51.5394, lng: -0.1432,
    summary: "Camden Caribbean diner with curry goat, jerk chicken and patties, open since the 1980s.",
    tags: ["jerk", "curry goat", "diner"],
    priceRange: "££",
    url: "https://www.mapetitejamaica.com/",
  },
  {
    id: "j-patty-co-covent",
    name: "Jamaica Patty Co.",
    country: "jamaica",
    type: "cafe",
    area: "Covent Garden",
    address: "26 New Row, Covent Garden, London WC2N 4LA",
    lat: 51.5117, lng: -0.1265,
    summary: "Patty-led counter with classic, jerk-chicken and saltfish fillings baked through the day.",
    tags: ["patties", "takeaway", "quick lunch"],
    priceRange: "£",
    url: "https://jamaicapatty.co.uk/",
  },
  {
    id: "j-negril",
    name: "Negril",
    country: "jamaica",
    type: "restaurant",
    area: "Brixton",
    address: "132 Brixton Hill, London SW2 1RS",
    lat: 51.4546, lng: -0.1213,
    summary: "Brixton Hill stalwart for jerk, ackee and saltfish, and a long Caribbean cocktail list.",
    tags: ["jerk", "ackee", "cocktails"],
    priceRange: "££",
    url: "https://negrilonline.co.uk/",
  },
  {
    id: "j-island-vibez",
    name: "Island Vibez",
    country: "jamaica",
    type: "restaurant",
    area: "Stratford",
    address: "Theatre Royal Bar & Kitchen, Gerry Raffles Square, London E15 1BN",
    lat: 51.5408, lng: -0.0021,
    summary: "East London Caribbean kitchen inside the Theatre Royal, with a mix of Jamaican and Trinidadian staples.",
    tags: ["caribbean", "theatre kitchen"],
    priceRange: "££",
  },
  {
    id: "j-cafe-caribbean",
    name: "Café Caribbean",
    country: "jamaica",
    type: "cafe",
    area: "Spitalfields",
    address: "Old Spitalfields Market, 16 Horner Square, London E1 6EW",
    lat: 51.5193, lng: -0.0750,
    summary: "Market stall doing brisk lunch trade in jerk, rice & peas and patties.",
    tags: ["market", "lunch", "patties"],
    priceRange: "£",
  },
  {
    id: "j-paradise-cove",
    name: "Paradise Cove",
    country: "jamaica",
    type: "restaurant",
    area: "Battersea",
    address: "55 Northcote Rd, Battersea, London SW11 1NP",
    lat: 51.4640, lng: -0.1700,
    summary: "Chef Tarell Mcintosh's neighbourhood Jamaican dining room with a creative, evolving menu.",
    tags: ["seasonal", "modern caribbean"],
    priceRange: "££",
  },
  {
    id: "z-inairobi",
    name: "iNairobi",
    country: "zimbabwe",
    type: "restaurant",
    area: "Crouch End",
    address: "17 High St, London N8 7PW",
    lat: 51.5840, lng: -0.1167,
    summary: "Pan-African restaurant in north London with southern-African dishes alongside east and west menus.",
    tags: ["pan-african", "boerewors"],
    priceRange: "££",
    featured: true,
    url: "https://inairobi.co.uk/",
  },
  {
    id: "z-cooking-with-caz",
    name: "Cooking With Caz",
    country: "zimbabwe",
    type: "supper-club",
    area: "London (varies)",
    address: "Various London venues — see website",
    lat: 51.5074, lng: -0.1278,
    summary: "Roaming supper-club and catering brand reimagining Zimbabwean food across London.",
    tags: ["supper club", "catering", "tasting"],
    priceRange: "£££",
    url: "https://cookingwithcaz.com/",
  },
  {
    id: "i-saravanaa-wembley",
    name: "Saravanaa Bhavan · Wembley",
    country: "india",
    type: "restaurant",
    area: "Wembley",
    address: "22 Ealing Rd, Wembley HA0 4TL",
    lat: 51.5559, lng: -0.3036,
    summary: "Global vegetarian South Indian chain with dosa, idli and full thalis.",
    tags: ["south indian", "vegetarian", "dosa"],
    priceRange: "£",
    url: "https://www.saravanabhavan.com/",
  },
  {
    id: "i-sakonis",
    name: "Sakonis",
    country: "india",
    type: "restaurant",
    area: "Wembley",
    address: "127-129 Ealing Rd, Wembley HA0 4BP",
    lat: 51.5547, lng: -0.3050,
    summary: "Long-running Gujarati vegetarian canteen on Ealing Road with chaats, dosas and Indo-Chinese.",
    tags: ["gujarati", "vegetarian", "chaat"],
    priceRange: "£",
  },
  {
    id: "i-brilliant",
    name: "The Brilliant",
    country: "india",
    type: "restaurant",
    area: "Southall",
    address: "72-76 Western Rd, Southall UB2 5DZ",
    lat: 51.5050, lng: -0.3829,
    summary: "Family-run Southall institution serving Punjabi classics for over forty years.",
    tags: ["punjabi", "methi chicken", "family-run"],
    priceRange: "££",
    url: "https://www.brilliantrestaurant.com/",
  },
  {
    id: "i-dosa-n-chutney",
    name: "Dosa n Chutney",
    country: "india",
    type: "restaurant",
    area: "Tooting",
    address: "68 Tooting High St, London SW17 0RN",
    lat: 51.4276, lng: -0.1681,
    summary: "Tooting specialist in South Indian dosas and idli sambar from morning to night.",
    tags: ["south indian", "dosa", "vegetarian"],
    priceRange: "£",
  },
  {
    id: "i-jaffna-house",
    name: "Jaffna House",
    country: "india",
    type: "restaurant",
    area: "Tooting",
    address: "90 Tooting High St, London SW17 0RN",
    lat: 51.4279, lng: -0.1681,
    summary: "Sri Lankan kitchen on Tooting High Street with hoppers, kothu and South Indian crossovers.",
    tags: ["sri lankan", "south indian", "hoppers"],
    priceRange: "£",
  },
];

export const EVENTS: EventItem[] = [
  {
    id: "e-semi-1-watch",
    title: "Semi 1 Watch Party · Nigeria vs Zimbabwe",
    country: "all",
    type: "watch-party",
    date: "Tuesday 26 May 2026",
    time: "7:00 pm",
    venue: "Tasty Woolwich, Plumstead Road",
    area: "Woolwich",
    lat: 51.4901, lng: 0.0732,
    summary: "Big screens five minutes from the ground. Doors at 6:30, kick-off 7:30.",
  },
  {
    id: "e-semi-2-watch",
    title: "Semi 2 Watch Party · India vs Jamaica",
    country: "all",
    type: "watch-party",
    date: "Wednesday 27 May 2026",
    time: "7:00 pm",
    venue: "Jatt & Juliet, Greenwich",
    area: "Greenwich",
    lat: 51.4889, lng: 0.0070,
    summary: "Crossover menu of Indian small plates and Caribbean patties for the second semi.",
  },
  {
    id: "e-pre-stadium",
    title: "Pre-Stadium Suya Pop-Up",
    country: "nigeria",
    type: "pop-up",
    date: "Tuesday 26 May 2026",
    time: "5:30 pm",
    venue: "Charlton Park gates",
    area: "Charlton",
    lat: 51.4870, lng: 0.0410,
    summary: "Smoke-grilled suya skewers on the walk from Charlton station to The Valley.",
  },
  {
    id: "e-zim-supper",
    title: "Warriors Send-Off Supper",
    country: "zimbabwe",
    type: "pop-up",
    date: "Sunday 24 May 2026",
    time: "1:00 pm",
    venue: "Cooking With Caz (venue TBC)",
    area: "Central London",
    lat: 51.5074, lng: -0.1278,
    summary: "Pop-up Zim supper club to send off the Warriors. Ticketed; sign up via the enquiry form.",
  },
  {
    id: "e-naija-meetup",
    title: "Naija Diaspora Meetup",
    country: "nigeria",
    type: "meetup",
    date: "Friday 22 May 2026",
    time: "6:30 pm",
    venue: "Chuku's, Tottenham",
    area: "Tottenham",
    lat: 51.5880, lng: -0.0700,
    summary: "Pre-tournament social with sharing plates and a highlife DJ from 8 pm.",
  },
  {
    id: "e-reggae-night",
    title: "Reggae Roots Night",
    country: "jamaica",
    type: "meetup",
    date: "Saturday 23 May 2026",
    time: "8:00 pm",
    venue: "Negril, Brixton",
    area: "Brixton",
    lat: 51.4546, lng: -0.1213,
    summary: "Sound-system set with three selectors. Jerk grill running through the night.",
  },
  {
    id: "e-5aside",
    title: "Diaspora 5-a-side Tournament",
    country: "all",
    type: "tournament",
    date: "Sunday 24 May 2026",
    time: "10:00 am",
    venue: "PowerLeague Charlton",
    area: "Charlton",
    lat: 51.4910, lng: 0.0290,
    summary: "Sixteen teams, four nations, one bracket. Sign up via the enquiry form.",
  },
  {
    id: "e-finals-brunch",
    title: "Grand Finals Day Brunch",
    country: "all",
    type: "watch-party",
    date: "Saturday 30 May 2026",
    time: "12:00 pm",
    venue: "Rifa's Caribbean, Charlton",
    area: "Charlton",
    lat: 51.4860, lng: 0.0370,
    summary: "Two games on the big screen, two minutes from the ground. Brunch from noon.",
  },
];

export const FEATURED_LISTINGS = LISTINGS.filter((l) => l.featured);
export const ALL_AREAS = Array.from(new Set(LISTINGS.map((l) => l.area))).sort();
