export type Country = "nigeria" | "jamaica" | "zimbabwe" | "india";

export const COUNTRIES: Record<
  Country,
  { name: string; flag: string; color: string; cuisine: string }
> = {
  nigeria: { name: "Nigeria", flag: "🇳🇬", color: "#008751", cuisine: "Nigerian" },
  jamaica: { name: "Jamaica", flag: "🇯🇲", color: "#ffb81c", cuisine: "Jamaican" },
  zimbabwe: { name: "Zimbabwe", flag: "🇿🇼", color: "#ef3340", cuisine: "Zimbabwean" },
  india:    { name: "India",    flag: "🇮🇳", color: "#ff671f", cuisine: "Indian" },
};

// Unity Cup 2026 is held at The Valley, home of Charlton Athletic FC.
export const STADIUM = {
  name: "The Valley",
  subtitle: "Charlton Athletic FC",
  address: "Floyd Rd, Charlton, London SE7 8BL",
  lat: 51.4865,
  lng: 0.0364,
};

export type LatLng = { lat: number; lng: number };

// Haversine — distance between two lat/lng points in km.
export function distanceKm(a: LatLng, b: LatLng): number {
  const R = 6371;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

export function formatDistance(km: number): string {
  if (km < 1) return `${Math.round(km * 1000)} m`;
  if (km < 10) return `${km.toFixed(1)} km`;
  return `${Math.round(km)} km`;
}

export type Listing = {
  id: string;
  name: string;
  country: Country;
  type: "restaurant" | "cafe" | "bar" | "market" | "supper-club";
  area: string;
  address: string;
  lat: number;
  lng: number;
  summary: string;
  tags: string[];
  priceRange: "£" | "££" | "£££";
  featured?: boolean;
  url?: string;
  phone?: string;
  instagram?: string; // handle without the @
  hours?: string; // seed/placeholder strings — verify per venue before going live
};

// Real London-based venues across the four cuisines. Listings near The Valley
// (Charlton / Woolwich / Greenwich / Lewisham / Blackheath) are concentrated
// first so the "near stadium" view has plenty to show.
export const LISTINGS: Listing[] = [
  // ===== Near The Valley · Charlton / Woolwich =====
  {
    id: "j-rifas",
    name: "Rifa's Caribbean Cuisine",
    country: "jamaica",
    type: "restaurant",
    area: "Charlton",
    address: "Flat 5, Gooding House, Valley Grove, Charlton, London SE7 8AT",
    lat: 51.4860, lng: 0.0370,
    summary: "Caribbean kitchen a few minutes from The Valley — jerk, curry goat and patties.",
    tags: ["jerk", "curry goat", "near stadium"],
    priceRange: "£",
    featured: true,
    hours: "Tue–Sun 12:00–22:00, Mon closed",
    },
  {
    id: "i-new-viceroy",
    name: "New Viceroy",
    country: "india",
    type: "restaurant",
    area: "Charlton Village",
    address: "10 The Village, Charlton, London SE7 8UD",
    lat: 51.4854, lng: 0.0339,
    summary: "Charlton Village Indian dining room — curry-house classics and a long tandoori list.",
    tags: ["curry house", "tandoori", "near stadium"],
    priceRange: "££",
    featured: true,
    phone: "+44 20 8319 3439",
    hours: "Daily 17:30–23:30",
    },
  {
    id: "i-kesar",
    name: "Kesar Punjabi Restaurant",
    country: "india",
    type: "restaurant",
    area: "Greenwich Peninsula",
    address: "192 Woolwich Rd, London SE7 7RA",
    lat: 51.4889, lng: 0.0234,
    summary: "Punjabi cooking on Woolwich Road, ten minutes' walk from the stadium.",
    tags: ["punjabi", "tandoori"],
    priceRange: "££",
    phone: "+44 20 7018 0230",
    hours: "Daily 12:00–23:00",
    },
  {
    id: "j-real-deal",
    name: "The Real Deal Authentic Jamaican",
    country: "jamaica",
    type: "restaurant",
    area: "Woolwich",
    address: "17 Plumstead Rd, Woolwich, London SE18 7BZ",
    lat: 51.4902, lng: 0.0735,
    summary: "Woolwich Jamaican kitchen with delivery across the SE7, SE18 and SE28 postcodes.",
    tags: ["jerk", "takeaway", "delivery"],
    priceRange: "£",
    hours: "Tue–Sun 12:00–22:00, Mon closed",
    instagram: "therealdealajc",
    },
  {
    id: "j-chefs-house",
    name: "Chef's House",
    country: "jamaica",
    type: "restaurant",
    area: "Plumstead",
    address: "128 Plumstead Common Rd, Woolwich, London SE18 2UL",
    lat: 51.4815, lng: 0.0855,
    summary: "Neighbourhood Caribbean dining room on Plumstead Common.",
    tags: ["caribbean", "family-friendly"],
    priceRange: "££",
    hours: "Mon–Sat 12:00–22:00",
    },
  {
    id: "j-sunjam",
    name: "Sunjam Caribbean",
    country: "jamaica",
    type: "cafe",
    area: "Woolwich",
    address: "13A Spray St, Woolwich, London SE18 6AP",
    lat: 51.4905, lng: 0.0680,
    summary: "Quick Caribbean takeaway off Powis Street.",
    tags: ["takeaway", "lunch"],
    priceRange: "£",
    hours: "Mon–Sat 11:00–21:00",
    },
  {
    id: "n-tasty-woolwich",
    name: "Tasty Woolwich",
    country: "nigeria",
    type: "restaurant",
    area: "Woolwich",
    address: "16 Plumstead Rd, Woolwich, London SE18 7BZ",
    lat: 51.4901, lng: 0.0732,
    summary: "Plumstead Road West African kitchen with jollof, egusi and pepper soup.",
    tags: ["jollof", "egusi"],
    priceRange: "£",
    featured: true,
    phone: "+44 20 8854 2171",
    hours: "Daily 12:00–22:00",
    },
  {
    id: "n-marys-takeaway",
    name: "Mary's Takeaway",
    country: "nigeria",
    type: "cafe",
    area: "Woolwich",
    address: "Unit 12, 125 Powis St, London SE18 6LQ",
    lat: 51.4906, lng: 0.0665,
    summary: "West African takeaway counter on Powis Street, popular for matchday lunches.",
    tags: ["takeaway", "matchday"],
    priceRange: "£",
    hours: "Mon–Sat 11:00–21:00",
    },
  {
    id: "n-ammas-fare",
    name: "Ammas Fare",
    country: "nigeria",
    type: "restaurant",
    area: "Woolwich",
    address: "179 Powis St, Woolwich, London SE18 6JL",
    lat: 51.4908, lng: 0.0664,
    summary: "Sit-down West African restaurant on the main Powis Street drag.",
    tags: ["sit-down", "west african"],
    priceRange: "££",
    phone: "+44 20 8854 0259",
    hours: "Daily 12:00–23:00",
    },
  {
    id: "n-favourite-african",
    name: "Favourite African Restaurant",
    country: "nigeria",
    type: "restaurant",
    area: "Plumstead",
    address: "233 Plumstead High St, London SE18 1HF",
    lat: 51.4877, lng: 0.0860,
    summary: "Plumstead High Street West African spot with a hearty buffet-style menu.",
    tags: ["buffet", "west african"],
    priceRange: "£",
    phone: "+44 20 3489 9543",
    hours: "Daily 12:00–22:00",
    },
  {
    id: "i-jatt-juliet",
    name: "Jatt & Juliet",
    country: "india",
    type: "bar",
    area: "Greenwich",
    address: "42 Woolwich Rd, London SE10 0JU",
    lat: 51.4889, lng: 0.0070,
    summary: "Modern Indian restaurant and bar between Greenwich and Charlton.",
    tags: ["modern indian", "cocktails"],
    priceRange: "££",
    hours: "Mon–Sun 12:00–24:00",
    },
  {
    id: "i-mountain-view",
    name: "Mountain View",
    country: "india",
    type: "restaurant",
    area: "Greenwich",
    address: "160 Trafalgar Rd, Greenwich, London SE10 9TZ",
    lat: 51.4825, lng: 0.0070,
    summary: "Greenwich Indian and Nepalese dining room near the Maritime Museum.",
    tags: ["indian", "nepalese"],
    priceRange: "££",
    phone: "+44 20 8858 0227",
    hours: "Daily 12:00–23:00",
    },
  {
    id: "i-coriander",
    name: "The Coriander",
    country: "india",
    type: "restaurant",
    area: "Blackheath",
    address: "1-3 Station Crescent, London SE3 7EQ",
    lat: 51.4690, lng: 0.0140,
    summary: "Blackheath Indian local serving traditional and contemporary plates.",
    tags: ["curry house"],
    priceRange: "££",
    phone: "+44 20 8858 7878",
    hours: "Daily 17:30–23:00",
    },

  // ===== Central & wider London =====
  {
    id: "n-ikoyi",
    name: "Ikoyi",
    country: "nigeria",
    type: "restaurant",
    area: "Strand",
    address: "180 Strand, London WC2R 1EA",
    lat: 51.5118, lng: -0.1163,
    summary: "Two-Michelin-star tasting menu drawing on West African ingredients and live-fire cooking.",
    tags: ["fine dining", "tasting menu", "michelin"],
    priceRange: "£££",
    featured: true,
    url: "https://ikoyilondon.com/",
    hours: "Tue–Sat 18:00–22:30",
    instagram: "ikoyi_london",
    },
  {
    id: "n-akoko",
    name: "Akoko",
    country: "nigeria",
    type: "restaurant",
    area: "Fitzrovia",
    address: "21 Berners St, London W1T 3LP",
    lat: 51.5188, lng: -0.1370,
    summary: "Michelin-starred West African fine dining with a chef's-counter view of the grill.",
    tags: ["fine dining", "tasting menu", "michelin"],
    priceRange: "£££",
    url: "https://akoko.co.uk/",
    hours: "Tue–Sat 18:00–22:30, Sat lunch 12:00–14:30",
    instagram: "akoko_london",
    },
  {
    id: "n-akara",
    name: "Akara",
    country: "nigeria",
    type: "restaurant",
    area: "Borough",
    address: "Stoney St, Borough Yards, London SE1",
    lat: 51.5050, lng: -0.0908,
    summary: "Crispy akara fritters with rotating fillings, anchored by an open kitchen in Borough Yards.",
    tags: ["fritters", "open kitchen", "lunch"],
    priceRange: "££",
    url: "https://www.akaralondon.co.uk/",
    hours: "Tue–Sun 12:00–22:30",
    instagram: "akara.london",
    },
  {
    id: "n-chukus",
    name: "Chuku's",
    country: "nigeria",
    type: "restaurant",
    area: "Tottenham",
    address: "274 High Rd, Tottenham, London N15 4AJ",
    lat: 51.5880, lng: -0.0700,
    summary: "Brother-and-sister-run Nigerian tapas restaurant with small plates designed for sharing.",
    tags: ["tapas", "small plates", "family-run"],
    priceRange: "££",
    url: "https://chukuslondon.co.uk/",
    hours: "Wed–Sun 17:00–22:30",
    instagram: "chukuslondon",
    },
  {
    id: "n-805-peckham",
    name: "805 Restaurant · Peckham",
    country: "nigeria",
    type: "restaurant",
    area: "Peckham",
    address: "153 Rye Ln, Peckham, London SE15 4TL",
    lat: 51.4717, lng: -0.0698,
    summary: "Long-running London Nigerian chain serving jollof, egusi, suya and grilled fish into the night.",
    tags: ["jollof", "suya", "late night"],
    priceRange: "££",
    url: "https://www.805restaurants.com/",
    hours: "Daily 12:00–24:00",
    instagram: "805restaurants",
    },
  {
    id: "n-eko",
    name: "Eko Wine Bar & Restaurant",
    country: "nigeria",
    type: "bar",
    area: "Homerton",
    address: "160 Homerton High St, London E9 6JA",
    lat: 51.5510, lng: -0.0440,
    summary: "Late-licence Nigerian wine bar with weekly live music and a hearty menu of home-style classics.",
    tags: ["wine bar", "live music", "late night"],
    priceRange: "££",
    hours: "Wed–Sun 17:00–02:00",
    },
  {
    id: "n-tatale",
    name: "Tatale",
    country: "nigeria",
    type: "restaurant",
    area: "Covent Garden",
    address: "The Africa Centre, 66 Great Suffolk St, London SE1 0BL",
    lat: 51.5036, lng: -0.0998,
    summary: "Modern West African plates from chef Akwasi Brenya-Mensa, named after a Ghanaian plantain dish.",
    tags: ["modern", "small plates"],
    priceRange: "£££",
    url: "https://www.tatale.co.uk/",
    hours: "Tue–Sat 18:00–22:30",
    instagram: "tatale.uk",
    },
  {
    id: "j-ma-petite",
    name: "Ma Petite Jamaica",
    country: "jamaica",
    type: "restaurant",
    area: "Camden",
    address: "9 Inverness St, Camden, London NW1 7HJ",
    lat: 51.5394, lng: -0.1432,
    summary: "Camden Caribbean diner with curry goat, jerk chicken and patties, open since the 1980s.",
    tags: ["jerk", "curry goat", "diner"],
    priceRange: "££",
    url: "https://www.mapetitejamaica.com/",
    hours: "Daily 12:00–23:00",
    instagram: "mapetitejamaica",
    },
  {
    id: "j-patty-co-covent",
    name: "Jamaica Patty Co.",
    country: "jamaica",
    type: "cafe",
    area: "Covent Garden",
    address: "26 New Row, Covent Garden, London WC2N 4LA",
    lat: 51.5117, lng: -0.1265,
    summary: "Patty-led counter with classic, jerk-chicken and saltfish fillings baked through the day.",
    tags: ["patties", "takeaway", "quick lunch"],
    priceRange: "£",
    url: "https://jamaicapatty.co.uk/",
    hours: "Mon–Sat 10:00–19:00",
    instagram: "jamaicapattyco",
    },
  {
    id: "j-negril",
    name: "Negril",
    country: "jamaica",
    type: "restaurant",
    area: "Brixton",
    address: "132 Brixton Hill, London SW2 1RS",
    lat: 51.4546, lng: -0.1213,
    summary: "Brixton Hill stalwart for jerk, ackee and saltfish, and a long Caribbean cocktail list.",
    tags: ["jerk", "ackee", "cocktails"],
    priceRange: "££",
    url: "https://negrilonline.co.uk/",
    hours: "Tue–Sun 17:00–23:00",
    instagram: "negrilbrixton",
    },
  {
    id: "j-island-vibez",
    name: "Island Vibez",
    country: "jamaica",
    type: "restaurant",
    area: "Stratford",
    address: "Theatre Royal Bar & Kitchen, Gerry Raffles Square, London E15 1BN",
    lat: 51.5408, lng: -0.0021,
    summary: "East London Caribbean kitchen inside the Theatre Royal, with a mix of Jamaican and Trinidadian staples.",
    tags: ["caribbean", "theatre kitchen"],
    priceRange: "££",
    hours: "Tue–Sun 12:00–23:00",
    },
  {
    id: "j-cafe-caribbean",
    name: "Café Caribbean",
    country: "jamaica",
    type: "cafe",
    area: "Spitalfields",
    address: "Old Spitalfields Market, 16 Horner Square, London E1 6EW",
    lat: 51.5193, lng: -0.0750,
    summary: "Market stall doing brisk lunch trade in jerk, rice & peas and patties.",
    tags: ["market", "lunch", "patties"],
    priceRange: "£",
    hours: "Daily 11:00–18:00",
    },
  {
    id: "j-paradise-cove",
    name: "Paradise Cove",
    country: "jamaica",
    type: "restaurant",
    area: "Battersea",
    address: "55 Northcote Rd, Battersea, London SW11 1NP",
    lat: 51.4640, lng: -0.1700,
    summary: "Chef Tarell Mcintosh's neighbourhood Jamaican dining room with a creative, evolving menu.",
    tags: ["seasonal", "modern caribbean"],
    priceRange: "££",
    hours: "Tue–Sun 12:00–23:00",
    instagram: "paradisecovelondon",
    },
  {
    id: "z-inairobi",
    name: "iNairobi",
    country: "zimbabwe",
    type: "restaurant",
    area: "Crouch End",
    address: "17 High St, London N8 7PW",
    lat: 51.5840, lng: -0.1167,
    summary: "Pan-African restaurant in north London with southern-African dishes alongside east and west menus.",
    tags: ["pan-african", "boerewors"],
    priceRange: "££",
    featured: true,
    url: "https://inairobi.co.uk/",
    hours: "Tue–Sun 14:00–23:00, Mon closed",
    instagram: "i.nairobi.london",
    },
  {
    id: "z-cooking-with-caz",
    name: "Cooking With Caz",
    country: "zimbabwe",
    type: "supper-club",
    area: "London (varies)",
    address: "Various London venues — see website",
    lat: 51.5074, lng: -0.1278,
    summary: "Roaming supper-club and catering brand reimagining Zimbabwean food across London.",
    tags: ["supper club", "catering", "tasting"],
    priceRange: "£££",
    url: "https://cookingwithcaz.com/",
    hours: "Monthly events — see website",
    instagram: "cookingwithcaz",
    },
  {
    id: "i-saravanaa-wembley",
    name: "Saravanaa Bhavan · Wembley",
    country: "india",
    type: "restaurant",
    area: "Wembley",
    address: "22 Ealing Rd, Wembley HA0 4TL",
    lat: 51.5559, lng: -0.3036,
    summary: "Global vegetarian South Indian chain with dosa, idli and full thalis.",
    tags: ["south indian", "vegetarian", "dosa"],
    priceRange: "£",
    url: "https://www.saravanabhavan.com/",
    hours: "Daily 10:00–22:30",
    instagram: "saravanabhavan_uk",
    },
  {
    id: "i-sakonis",
    name: "Sakonis",
    country: "india",
    type: "restaurant",
    area: "Wembley",
    address: "127-129 Ealing Rd, Wembley HA0 4BP",
    lat: 51.5547, lng: -0.3050,
    summary: "Long-running Gujarati vegetarian canteen on Ealing Road with chaats, dosas and Indo-Chinese.",
    tags: ["gujarati", "vegetarian", "chaat"],
    priceRange: "£",
    hours: "Daily 12:00–22:30",
    },
  {
    id: "i-brilliant",
    name: "The Brilliant",
    country: "india",
    type: "restaurant",
    area: "Southall",
    address: "72-76 Western Rd, Southall UB2 5DZ",
    lat: 51.5050, lng: -0.3829,
    summary: "Family-run Southall institution serving Punjabi classics for over forty years.",
    tags: ["punjabi", "methi chicken", "family-run"],
    priceRange: "££",
    url: "https://www.brilliantrestaurant.com/",
    hours: "Tue–Sun 18:00–23:00, Mon closed",
    instagram: "thebrilliantrestaurant",
    },
  {
    id: "i-dosa-n-chutney",
    name: "Dosa n Chutney",
    country: "india",
    type: "restaurant",
    area: "Tooting",
    address: "68 Tooting High St, London SW17 0RN",
    lat: 51.4276, lng: -0.1681,
    summary: "Tooting specialist in South Indian dosas and idli sambar from morning to night.",
    tags: ["south indian", "dosa", "vegetarian"],
    priceRange: "£",
    hours: "Daily 11:00–22:30",
    },
  {
    id: "i-jaffna-house",
    name: "Jaffna House",
    country: "india",
    type: "restaurant",
    area: "Tooting",
    address: "90 Tooting High St, London SW17 0RN",
    lat: 51.4279, lng: -0.1681,
    summary: "Sri Lankan kitchen on Tooting High Street with hoppers, kothu and South Indian crossovers.",
    tags: ["sri lankan", "south indian", "hoppers"],
    priceRange: "£",
    hours: "Daily 11:00–22:30",
    },

  // ===== Added from general searches =====
  {
    id: "n-alhaji-suya-peckham",
    name: "Alhaji Suya",
    country: "nigeria",
    type: "restaurant",
    area: "Peckham",
    address: "25 Peckham Park Rd, London SE15 6TR",
    lat: 51.4750, lng: -0.0670,
    summary: "Northern Nigerian suya kiosk — lamb, chicken and tozo beef under the yaji spice blend.",
    tags: ["suya", "northern nigerian", "kiosk"],
    priceRange: "£",
    hours: "Tue–Sun 13:00–22:00, Mon closed",
    instagram: "alhajisuya",
  },
  {
    id: "n-flygerians",
    name: "The Flygerians",
    country: "nigeria",
    type: "restaurant",
    area: "Peckham",
    address: "Peckham Palms, 14a Bournemouth Close, London SE15 4PB",
    lat: 51.4716, lng: -0.0688,
    summary: "Sister-run Peckham Palms kitchen turning grandmother recipes into a community supper club.",
    tags: ["family-run", "community", "small plates"],
    priceRange: "££",
    hours: "Thu–Sun 17:00–22:30",
    instagram: "theflygerians",
  },
  {
    id: "n-lolak-afrique",
    name: "Lolak Afrique",
    country: "nigeria",
    type: "restaurant",
    area: "Peckham",
    address: "36 Choumert Rd, Peckham, London SE15 4SE",
    lat: 51.4710, lng: -0.0700,
    summary: "Choumert Road bukka serving Lagos home-style staples — efo, ogbono, pounded yam.",
    tags: ["bukka", "home cooking"],
    priceRange: "£",
    hours: "Tue–Sun 12:00–22:00, Mon closed",
  },
  {
    id: "n-cafe-spice",
    name: "Café Spice",
    country: "nigeria",
    type: "cafe",
    area: "Peckham",
    address: "Rye Lane, Peckham, London SE15",
    lat: 51.4720, lng: -0.0695,
    summary: "Rye Lane snack counter with puff-puff, suya, tilapia and jollof.",
    tags: ["snacks", "puff-puff", "takeaway"],
    priceRange: "£",
    hours: "Mon–Sat 10:00–21:00",
  },
  {
    id: "j-cottons-camden",
    name: "Cottons · Camden",
    country: "jamaica",
    type: "restaurant",
    area: "Camden",
    address: "55 Chalk Farm Rd, London NW1 8AN",
    lat: 51.5430, lng: -0.1480,
    summary: "Chalk Farm Caribbean dining room with an 80-strong rum list and live music nights.",
    tags: ["rum bar", "live music", "jerk"],
    priceRange: "££",
    hours: "Daily 12:00–24:00",
    url: "https://www.cottons-restaurant.co.uk/",
    instagram: "cottonsrestaurants",
  },
  {
    id: "j-cottons-shoreditch",
    name: "Cottons · Shoreditch",
    country: "jamaica",
    type: "restaurant",
    area: "Shoreditch",
    address: "70 Great Eastern St, London EC2A 3JL",
    lat: 51.5253, lng: -0.0830,
    summary: "Shoreditch sibling of the Camden Caribbean staple — same big rum list, same jerk pit.",
    tags: ["rum bar", "jerk"],
    priceRange: "££",
    hours: "Daily 12:00–24:00",
    url: "https://www.cottons-restaurant.co.uk/",
  },
  {
    id: "j-fish-wings-tings",
    name: "Fish, Wings & Tings",
    country: "jamaica",
    type: "restaurant",
    area: "Brixton",
    address: "Brixton Village, 99 Coldharbour Ln, London SW9 8PR",
    lat: 51.4623, lng: -0.1135,
    summary: "Brixton Village shop run by chef Brian Danclair, doing Trinidadian-Caribbean small plates.",
    tags: ["caribbean", "small plates", "market"],
    priceRange: "££",
    hours: "Wed–Sun 12:00–22:00",
    instagram: "fish_wings_tings",
  },
  {
    id: "j-2210-nattycancook",
    name: "2210 by NattyCanCook",
    country: "jamaica",
    type: "restaurant",
    area: "Herne Hill",
    address: "Norwood Rd, Herne Hill, London SE24",
    lat: 51.4530, lng: -0.1010,
    summary: "Herne Hill neighbourhood Caribbean kitchen with ital stews and weekend brunch.",
    tags: ["ital", "brunch", "neighbourhood"],
    priceRange: "££",
    hours: "Wed–Sun 11:00–22:00",
    instagram: "nattycancook",
  },
  {
    id: "j-ochi",
    name: "Ochi",
    country: "jamaica",
    type: "restaurant",
    area: "Shepherd's Bush",
    address: "152 Uxbridge Rd, London W12 8AA",
    lat: 51.5060, lng: -0.2280,
    summary: "Shepherd's Bush stalwart, three decades on the Uxbridge Road serving jerk and curry goat.",
    tags: ["jerk", "curry goat", "long-running"],
    priceRange: "££",
    hours: "Tue–Sun 12:00–23:00, Mon closed",
  },
  {
    id: "j-caribbean-kitchen-hackney",
    name: "Caribbean Kitchen Hackney",
    country: "jamaica",
    type: "restaurant",
    area: "Hackney",
    address: "67 Mare St, London E8 4RG",
    lat: 51.5425, lng: -0.0550,
    summary: "Mare Street kitchen turning out jerk pork, fish festival and oxtail through the day.",
    tags: ["jerk pork", "oxtail", "festival"],
    priceRange: "£",
    hours: "Mon–Sat 11:00–22:00",
  },
  {
    id: "j-octaves-kitchen",
    name: "Octaves Kitchen",
    country: "jamaica",
    type: "restaurant",
    area: "Stoke Newington",
    address: "Stoke Newington, London N16",
    lat: 51.5630, lng: -0.0750,
    summary: "Stoke Newington all-you-can-eat small-plates concept with a rotating Caribbean menu.",
    tags: ["small plates", "all you can eat"],
    priceRange: "££",
    hours: "Thu–Sun 17:00–22:30",
    url: "https://www.octaveskitchen.co.uk/",
    instagram: "octaveskitchen",
  },
  {
    id: "j-peppers-and-spice",
    name: "Peppers & Spice",
    country: "jamaica",
    type: "restaurant",
    area: "Dalston",
    address: "Ball's Pond Rd, Dalston, London N1",
    lat: 51.5450, lng: -0.0770,
    summary: "Ball's Pond Road Caribbean room featured on Anthony Bourdain's London episode.",
    tags: ["caribbean", "long-running"],
    priceRange: "£",
    hours: "Mon–Sat 12:00–22:00",
  },
  {
    id: "j-rainbow-bakery",
    name: "Rainbow Bakery",
    country: "jamaica",
    type: "cafe",
    area: "Dalston",
    address: "Dalston, London E8",
    lat: 51.5450, lng: -0.0760,
    summary: "Dalston Caribbean bakery, in the same family hands since 1987 — patties, cassava cake, spiced bun.",
    tags: ["bakery", "patties", "family-run"],
    priceRange: "£",
    hours: "Mon–Sat 08:00–19:00",
  },
  {
    id: "i-aladin",
    name: "Aladin",
    country: "india",
    type: "restaurant",
    area: "Brick Lane",
    address: "132 Brick Ln, London E1 6RU",
    lat: 51.5210, lng: -0.0720,
    summary: "Brick Lane curry-house institution running since 1979.",
    tags: ["curry house", "long-running", "bangladeshi"],
    priceRange: "££",
    hours: "Daily 12:00–24:00",
  },
  {
    id: "i-sheba",
    name: "Sheba",
    country: "india",
    type: "restaurant",
    area: "Brick Lane",
    address: "136 Brick Ln, London E1 6RU",
    lat: 51.5212, lng: -0.0720,
    summary: "Two-floor Brick Lane curry house, on the strip since 1974.",
    tags: ["curry house", "long-running"],
    priceRange: "££",
    hours: "Daily 12:00–24:00",
    url: "https://www.shebabricklane.com/",
  },
  {
    id: "i-bengal-village",
    name: "Bengal Village",
    country: "india",
    type: "restaurant",
    area: "Brick Lane",
    address: "75 Brick Ln, London E1 6QL",
    lat: 51.5206, lng: -0.0720,
    summary: "Family-run Brick Lane curry house with a long-time following for consistency.",
    tags: ["curry house", "bangladeshi", "family-run"],
    priceRange: "££",
    hours: "Daily 12:00–24:00",
    url: "https://bengalvillagebricklane.co.uk/",
  },

  // ===== Added from second batch =====
  {
    id: "i-thattukada",
    name: "Thattukada",
    country: "india",
    type: "restaurant",
    area: "East Ham",
    address: "High St North, East Ham, London E6",
    lat: 51.5395, lng: 0.0540,
    summary: "Husband-and-wife Keralan kitchen, a hub for the East Ham Malayali community.",
    tags: ["keralan", "south indian", "family-run"],
    priceRange: "££",
    hours: "Tue–Sun 11:30–22:30, Mon closed",
  },
  {
    id: "i-saravanaa-east-ham",
    name: "Saravana Bhavan · East Ham",
    country: "india",
    type: "restaurant",
    area: "East Ham",
    address: "300 High St North, East Ham, London E12 6SA",
    lat: 51.5398, lng: 0.0560,
    summary: "East Ham branch of the global vegetarian South Indian chain — dosa, idli, full thalis.",
    tags: ["south indian", "vegetarian", "dosa"],
    priceRange: "£",
    hours: "Daily 09:00–22:30",
    url: "https://www.saravanabhavan.com/",
  },
  {
    id: "i-sangeetha-east-ham",
    name: "Sangeetha",
    country: "india",
    type: "restaurant",
    area: "East Ham",
    address: "194 High St North, East Ham, London E6 2JA",
    lat: 51.5392, lng: 0.0555,
    summary: "100% vegetarian South Indian restaurant on East Ham High Street.",
    tags: ["vegetarian", "south indian"],
    priceRange: "£",
    hours: "Daily 10:00–22:30",
  },
  {
    id: "i-sri-rathiga",
    name: "Sri Rathiga",
    country: "india",
    type: "restaurant",
    area: "East Ham",
    address: "High St North, East Ham, London E6",
    lat: 51.5396, lng: 0.0548,
    summary: "Pure-veg counter on East Ham's High Street North — dosa, idli and chaat through the day.",
    tags: ["vegetarian", "chaat", "dosa"],
    priceRange: "£",
    hours: "Daily 10:00–22:30",
  },
  {
    id: "i-lahore-kebab-house",
    name: "Lahore Kebab House",
    country: "india",
    type: "restaurant",
    area: "Whitechapel",
    address: "2-10 Umberston St, London E1 1PY",
    lat: 51.5145, lng: -0.0640,
    summary: "Whitechapel Punjabi-Pakistani institution — kebabs, karahi and slow-cooked nihari.",
    tags: ["punjabi", "pakistani", "halal"],
    priceRange: "££",
    hours: "Daily 12:00–24:00",
  },
  {
    id: "n-afrikana-mile-end",
    name: "Afrikana · Mile End",
    country: "nigeria",
    type: "restaurant",
    area: "Mile End",
    address: "231 Mile End Rd, London E1 4AA",
    lat: 51.5232, lng: -0.0440,
    summary: "Pan-African dining room on Mile End Road blending Nigerian, Ghanaian and other West African flavours.",
    tags: ["pan-african", "modern", "halal"],
    priceRange: "££",
    hours: "Daily 12:00–23:00",
    instagram: "afrikana_ukofficial",
  },
  {
    id: "n-princelyn",
    name: "Princelyn",
    country: "nigeria",
    type: "restaurant",
    area: "Bethnal Green",
    address: "477 Bethnal Green Rd, London E2 9QX",
    lat: 51.5288, lng: -0.0625,
    summary: "Bethnal Green Nigerian kitchen plating stews, peppered meats and assorted snacks.",
    tags: ["west african", "peppered meat"],
    priceRange: "££",
    hours: "Tue–Sun 12:00–22:30, Mon closed",
    url: "https://www.princelyn.com/",
  },
  {
    id: "j-dutchie",
    name: "The Dutchie",
    country: "jamaica",
    type: "restaurant",
    area: "South Norwood",
    address: "88 Whitehorse Ln, London SE25 6RQ",
    lat: 51.4060, lng: -0.0810,
    summary: "South Norwood Caribbean restaurant and bar — jerk pit, rum punch and late hours.",
    tags: ["jerk", "rum bar"],
    priceRange: "££",
    hours: "Tue–Sun 13:00–24:00, Mon closed",
  },
  {
    id: "z-its-nice-to-be-here-bham",
    name: "It's Nice To Be Here",
    country: "zimbabwe",
    type: "restaurant",
    area: "Birmingham",
    address: "Birmingham, West Midlands",
    lat: 52.4862, lng: -1.8904,
    summary: "Zim-owned Birmingham restaurant-pub with sadza, braai and a beer garden — worth the trip for diaspora food.",
    tags: ["sadza", "braai", "birmingham"],
    priceRange: "££",
    hours: "Tue–Sun 12:00–23:30, Mon closed",
  },
];
export const FEATURED_LISTINGS = LISTINGS.filter((l) => l.featured);
export const ALL_AREAS = Array.from(new Set(LISTINGS.map((l) => l.area))).sort();
